version: "3.7"
services:
  php:
    build:
      context: "./"
      target: php_production
    image: ${CONTAINER_REGISTRY_BASE}/php
    restart: always
    environment:
      APP_ENV: ${APP_ENV:-prod}
      APP_SECRET: ${APP_SECRET:?Missing mandatory value for $APP_SECRET}
      DATABASE_URL: ${DATABASE_URL:?Missing mandatory value for $DATABASE_URL}
      JWT_PRIVATE_KEY_PATH: ${JWT_PRIVATE_KEY_PATH:-config/jwt/private.pem}
      JWT_PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_PATH:-config/jwt/public.pem}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE:?Missing mandatory value for $JWT_PASSPHRASE}
      JWT_TOKEN_TTL: ${JWT_TOKEN_TTL:-3600}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:?Missing mandatory value for $CORS_ALLOW_ORIGIN}
      APP_HOST: ${APP_HOST:?Missing mandatory value for $APP_HOST}
      APP_SCHEME: ${APP_SCHEME:-https}
      APP_URL: ${APP_URL:?Missing mandatory value for $APP_URL}
    volumes:
      - "ergonode_multimedia:/srv/app/public/mutimedia"
      - "ergonode_import:/srv/app/import"
  node:
    build:
      context: "./"
      target: node_production
    image: ${CONTAINER_REGISTRY_BASE}/node
    restart: always
    environment:
      APP_ENV: ${APP_ENV:-prod}
      API_PROTOCOL: ${API_PROTOCOL:-https}
      API_HOST: ${API_HOST:?Missing mandatory value for $API_HOST}
      API_PREFIX: ${API_PREFIX:-/api/v1/}

  nginx:
    build:
      context: "./"
      target: nginx_production
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    restart: always
    environment:
      APP_ENV: ${APP_ENV:-prod}
      PHP_UPSTREAM_HOST: ${PHP_UPSTREAM_HOST:-php}
      DOLLAR: "$$"
    volumes:
      - "ergonode_multimedia:/srv/app/public/mutimedia"
    ports:
      - "${EXPOSED_NGINX_PORT:-80}:80"
volumes:
  ergonode_multimedia:
  ergonode_import:
