version: "3.7"
services:
  rabbitmq:
    image: ${CONTAINER_REGISTRY_BASE}/rabbitmq:${IMAGE_TAG:-latest}
    build:
      context: "./"
      dockerfile: Dockerfile-rabbitmq
      target: rabbitmq-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-ergonode}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-ergonode}
      CONSUL_HOST: 172.16.120.171
    networks:
      test:
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        failure_action: rollback
        order: start-first
    ports:
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    cap_add:
      - ALL
networks:
  test:
volumes:
  rabbitmq: