version: "3.7"
services:
  rabbit1:
    build:
      context: "./"
      dockerfile: Dockerfile-rabbitmq
      target: rabbitmq-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-ergonode}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-ergonode}
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
      RABBITMQ_USE_LONGNAME: 'true'
    ports:
      - "15673:15672"
    networks:
      test:
        aliases:
          - rabbitmq

  rabbit2:
#    image: "rabbitmq:3.8-alpine"
    build:
      context: "./"
      dockerfile: Dockerfile-rabbitmq
      target: rabbitmq-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-ergonode}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-ergonode}
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
      RABBITMQ_USE_LONGNAME: 'true'
    networks:
      test:
        aliases:
          - rabbitmq
    command: rabbitmq-server -detached
networks:
  test:
volumes:
  rabbitmq:
  rabbitmq2:
